POST https://localhost:7168/breakfasts
Content-Type: application/json

{
    "name": "Vegan breakfast 2",
    "description": "Vegan breakfast with oatmeal, avocado toast, omelette, salad and cookie. And coffee of course.",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "sweet": [
        "Cookie"
    ]
}

###

GET https://localhost:7094/Breakfasts/e35daaba-5a9e-43a2-9305-3dead8296fe0