@id=fc82cfff-ce5d-45c3-bdfb-6b777030e78b

PUT https://localhost:7168/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "Vegan Sunshine 5",
    "description": "Vegan everything! Join us for a healthy breakfast..",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}